version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: playbookwiz-postgres
    environment:
      POSTGRES_DB: playbookwiz
      POSTGRES_USER: playbookwiz
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - playbookwiz-network

  # MongoDB Database
  mongodb:
    image: mongo:7-jammy
    container_name: playbookwiz-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: playbookwiz
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: playbookwiz
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - playbookwiz-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: playbookwiz-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - playbookwiz-network

  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: playbookwiz-backend
    environment:
      - DATABASE_URL=postgresql://playbookwiz:password@postgres:5432/playbookwiz
      - MONGODB_URL=mongodb://playbookwiz:password@mongodb:27017/playbookwiz
      - REDIS_URL=redis://redis:6379
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - uploads_data:/app/uploads
    depends_on:
      - postgres
      - mongodb
      - redis
    networks:
      - playbookwiz-network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # Frontend Application
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: playbookwiz-frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - playbookwiz-network
    command: npm run dev

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
  uploads_data:

networks:
  playbookwiz-network:
    driver: bridge
