name: CI

on:
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: ./.tools/codex/setup.sh
      - name: Run frontend tests
        run: npm run test:frontend
      - name: Run backend tests
        run: npm run test:backend
